#Demonstração NumPY
###Fundamentos de Big Data e Data Science
###Aula 6
###Prof. Msc. Ailton J. Santos

#Importar Biblioteca

In [2]:
import numpy as np

#Gerar Dados Aleatórios

##Gerar um NDArray de 2x3 (duas lista com 3 elementos)

In [11]:
dados=np.random.randint(0,10, size = (3,3))

In [12]:
dados

array([[3, 4, 9],
       [8, 1, 0],
       [8, 3, 2]])

In [ ]:
A = [[7,8,10],[9,5,4],[0,1,3]]
print(A)
print(A[1][0])

A_array =np.array(A)

print(A_array)

[[7, 8, 10], [9, 5, 4], [0, 1, 3]]
9
[[ 7  8 10]
 [ 9  5  4]
 [ 0  1  3]]


#Tipo do Array

In [13]:
dados.dtype

dtype('int64')

#Tamanho e quantidade de dimensões

In [14]:
dados.shape

(3, 3)

In [15]:
dados.ndim

2

#Criar ndarray usando a função array
##Ao criar o array a função array tenta utilizar o melhor tipo de dado

In [16]:
lista=[1,2,5,7.8,1.25]

In [17]:
dados2=np.array(lista)

In [18]:
dados2

array([1.  , 2.  , 5.  , 7.8 , 1.25])

In [19]:
dados2.dtype

dtype('float64')

In [22]:
lista2=[[1,2,3],[4,3,2], [8, 9, 7]]
print(lista2)

[[1, 2, 3], [4, 3, 2], [8, 9, 7]]


In [23]:
dados3=np.array(lista2)

In [24]:
dados3

array([[1, 2, 3],
       [4, 3, 2],
       [8, 9, 7]])

In [25]:
dados2.dtype

dtype('float64')

#Outras maneiras de criar arrays

In [26]:
dadoszero=np.zeros(10)

In [28]:
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
dadoszero2=np.zeros((3,3))

In [30]:
dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
dadosum=np.ones(5)

In [32]:
dadosum

array([1., 1., 1., 1., 1.])

In [33]:
dadosseq=np.arange(10)

In [34]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
dadosseq2=np.arange(0,20,2)

In [36]:
dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
dadosseq.dtype

dtype('int64')

In [38]:
dadosseqf=dadosseq.astype(np.float64)

In [ ]:
dadosseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
dadosseqf.dtype

dtype('float64')

#Aritmética com Arrays

In [39]:
dados4=np.array([[1,2,3],[4,5,6]])

In [40]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
dados4*dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [42]:
dados4-dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [43]:
1/dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [44]:
dados5=dados4+dados4

In [45]:
dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [46]:
dados9=np.array([[8,2,3],[4,2,6]])

In [47]:
dados9

array([[8, 2, 3],
       [4, 2, 6]])

In [48]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
dados5*10

array([[ 20,  40,  60],
       [ 80, 100, 120]])

In [50]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
dados9>=dados4

array([[ True,  True,  True],
       [ True, False,  True]])

#Indexação

In [71]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

In [53]:
dados66=np.array([55,2,3,8,9,60,45,54])

In [54]:
print(dados66[1:7])

[ 2  3  8  9 60 45]


In [55]:
for i in range(8):
  print(dados66[i])

55
2
3
8
9
60
45
54


## Diferente de uma lista python, um recorte (fatia) de um ndarray sofrerá broadcast - é como se fosse uma view de bando de dados.
##Com conjuntos imensos de dados isso é uma grande vantagem em relação a performance

In [56]:
dadosseq[3:6]

array([3, 4, 5])

In [58]:
dadosseq[3:6]=20

In [59]:
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [62]:
fatiadados=dadosseq[2:4]

In [64]:
fatiadados

array([ 2, 20])

In [65]:
fatiadados[1]=2000

In [66]:
fatiadados

array([   2, 2000])

In [67]:
dadosseq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [69]:
fatiadados[:]=333

In [70]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

#Copiar dados

In [73]:
fatia2=dadosseq[2:4].copy()

In [74]:
fatia2

array([333, 333])

In [75]:
fatia2[:]=111

In [76]:
fatia2

array([111, 111])

In [77]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

#Array com mais de uma dimensão

In [ ]:
dados6=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
dados6[1,2]

np.int64(6)

#Máscaras

In [ ]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

In [ ]:
mascara=(dadosseq<100)

In [ ]:
mascara

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
dadosseq[dadosseq<20]=8888

In [ ]:
dadosseq

array([8888, 8888,  333,  333,   20,   20, 8888, 8888, 8888, 8888])

#Transposição

In [ ]:
dados7=np.arange(15).reshape((3,5))

In [ ]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#Multiplicação de Matrizes com Dots

In [ ]:
np.dot(dados7.T,dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

# Vejam que há muitas outras funções que podem ser exploradas como: sin, cos, power, mod, sqrt entre outros